
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IES
    username: root
    password: root

  ## Jpa config ##

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true