##logging config

logging:
  level:
    root: OFF


## DataSource information ##

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IES
    username: root
    password: root

## Jpa config ##

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
##SMTP PROPERTIES
  mail:
    host: smtp.gmail.com
    password: ******
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ankitnathbpl@gmail.com